[server]
port = 80
enableStaticServing = true

[client]
showSidebarNavigation = false


[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="monospace"
